#!/bin/bash

# win-bins : helper script that deletes linux-specific binaries and libs from
#            root dir and copy the windows-specific versions to it
#
# @author Ced-le-pingouin <Ced.le.pingouin@gmail.com>

#   Copyright (C) 2009 Cédric FLOQUET
#   
#   This file is part of Micro Lua DS Simulator.
#   
#   Micro Lua DS Simulator is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   Micro Lua DS Simulator is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with Micro Lua DS Simulator.  If not, see <http://www.gnu.org/licenses/>.

OLD_DIR=$PWD
SCRIPT_DIR=$(dirname $0)
cd $SCRIPT_DIR/..

## delete linux libs
rm -f ./*.so ./lua ./mls ./mls-src

## copy win libs
DIST_DIR=dist/win
cp $DIST_DIR/*.dll $DIST_DIR/*lua.exe $DIST_DIR/mls.bat $DIST_DIR/mls-src.bat .

cd $OLD_DIR